# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fademike/Yandex.Disk/ubuntu/project/git/flyLinuxServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fademike/Yandex.Disk/ubuntu/project/git/flyLinuxServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fademike/Yandex.Disk/ubuntu/project/git/flyLinuxServer/CMakeFiles /home/fademike/Yandex.Disk/ubuntu/project/git/flyLinuxServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fademike/Yandex.Disk/ubuntu/project/git/flyLinuxServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

ModemControl.o: ModemControl.c.o
.PHONY : ModemControl.o

# target to build an object file
ModemControl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ModemControl.c.o
.PHONY : ModemControl.c.o

ModemControl.i: ModemControl.c.i
.PHONY : ModemControl.i

# target to preprocess a source file
ModemControl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ModemControl.c.i
.PHONY : ModemControl.c.i

ModemControl.s: ModemControl.c.s
.PHONY : ModemControl.s

# target to generate assembly for a file
ModemControl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ModemControl.c.s
.PHONY : ModemControl.c.s

cb.o: cb.c.o
.PHONY : cb.o

# target to build an object file
cb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cb.c.o
.PHONY : cb.c.o

cb.i: cb.c.i
.PHONY : cb.i

# target to preprocess a source file
cb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cb.c.i
.PHONY : cb.c.i

cb.s: cb.c.s
.PHONY : cb.s

# target to generate assembly for a file
cb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/cb.c.s
.PHONY : cb.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main.c.s
.PHONY : main.c.s

mavlink_handler.o: mavlink_handler.c.o
.PHONY : mavlink_handler.o

# target to build an object file
mavlink_handler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mavlink_handler.c.o
.PHONY : mavlink_handler.c.o

mavlink_handler.i: mavlink_handler.c.i
.PHONY : mavlink_handler.i

# target to preprocess a source file
mavlink_handler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mavlink_handler.c.i
.PHONY : mavlink_handler.c.i

mavlink_handler.s: mavlink_handler.c.s
.PHONY : mavlink_handler.s

# target to generate assembly for a file
mavlink_handler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/mavlink_handler.c.s
.PHONY : mavlink_handler.c.s

nRF24.o: nRF24.c.o
.PHONY : nRF24.o

# target to build an object file
nRF24.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/nRF24.c.o
.PHONY : nRF24.c.o

nRF24.i: nRF24.c.i
.PHONY : nRF24.i

# target to preprocess a source file
nRF24.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/nRF24.c.i
.PHONY : nRF24.c.i

nRF24.s: nRF24.c.s
.PHONY : nRF24.s

# target to generate assembly for a file
nRF24.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/nRF24.c.s
.PHONY : nRF24.c.s

network.o: network.c.o
.PHONY : network.o

# target to build an object file
network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/network.c.o
.PHONY : network.c.o

network.i: network.c.i
.PHONY : network.i

# target to preprocess a source file
network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/network.c.i
.PHONY : network.c.i

network.s: network.c.s
.PHONY : network.s

# target to generate assembly for a file
network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/network.c.s
.PHONY : network.c.s

params.o: params.c.o
.PHONY : params.o

# target to build an object file
params.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/params.c.o
.PHONY : params.c.o

params.i: params.c.i
.PHONY : params.i

# target to preprocess a source file
params.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/params.c.i
.PHONY : params.c.i

params.s: params.c.s
.PHONY : params.s

# target to generate assembly for a file
params.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/params.c.s
.PHONY : params.c.s

program_pack.o: program_pack.c.o
.PHONY : program_pack.o

# target to build an object file
program_pack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/program_pack.c.o
.PHONY : program_pack.c.o

program_pack.i: program_pack.c.i
.PHONY : program_pack.i

# target to preprocess a source file
program_pack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/program_pack.c.i
.PHONY : program_pack.c.i

program_pack.s: program_pack.c.s
.PHONY : program_pack.s

# target to generate assembly for a file
program_pack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/program_pack.c.s
.PHONY : program_pack.c.s

si4463.o: si4463.c.o
.PHONY : si4463.o

# target to build an object file
si4463.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/si4463.c.o
.PHONY : si4463.c.o

si4463.i: si4463.c.i
.PHONY : si4463.i

# target to preprocess a source file
si4463.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/si4463.c.i
.PHONY : si4463.c.i

si4463.s: si4463.c.s
.PHONY : si4463.s

# target to generate assembly for a file
si4463.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/si4463.c.s
.PHONY : si4463.c.s

spi.o: spi.c.o
.PHONY : spi.o

# target to build an object file
spi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/spi.c.o
.PHONY : spi.c.o

spi.i: spi.c.i
.PHONY : spi.i

# target to preprocess a source file
spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/spi.c.i
.PHONY : spi.c.i

spi.s: spi.c.s
.PHONY : spi.s

# target to generate assembly for a file
spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/spi.c.s
.PHONY : spi.c.s

tty.o: tty.c.o
.PHONY : tty.o

# target to build an object file
tty.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tty.c.o
.PHONY : tty.c.o

tty.i: tty.c.i
.PHONY : tty.i

# target to preprocess a source file
tty.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tty.c.i
.PHONY : tty.c.i

tty.s: tty.c.s
.PHONY : tty.s

# target to generate assembly for a file
tty.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/tty.c.s
.PHONY : tty.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... ModemControl.o"
	@echo "... ModemControl.i"
	@echo "... ModemControl.s"
	@echo "... cb.o"
	@echo "... cb.i"
	@echo "... cb.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mavlink_handler.o"
	@echo "... mavlink_handler.i"
	@echo "... mavlink_handler.s"
	@echo "... nRF24.o"
	@echo "... nRF24.i"
	@echo "... nRF24.s"
	@echo "... network.o"
	@echo "... network.i"
	@echo "... network.s"
	@echo "... params.o"
	@echo "... params.i"
	@echo "... params.s"
	@echo "... program_pack.o"
	@echo "... program_pack.i"
	@echo "... program_pack.s"
	@echo "... si4463.o"
	@echo "... si4463.i"
	@echo "... si4463.s"
	@echo "... spi.o"
	@echo "... spi.i"
	@echo "... spi.s"
	@echo "... tty.o"
	@echo "... tty.i"
	@echo "... tty.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

